# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a91ad0e3d59a3f7a7b304f9351dfcb067b1ff9904c0863c036bfec8673d39cc9f793543ebf1e63cfdf86bc0b8621ae97afa80b5a8de8c7b958d62358cfd2f12

test:
  secret_key_base: c8a62a57cfc50e4962a0fde660f342fdc49396328230f025109d9ac04d9745469d45baf52430fdbc06076cb32636e5df7f322c2f466c2db115f760c23660775e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
